[project]
name = "ezcv"
version = "0.1.0"
requires-python = ">=3.10.0"
dependencies = [
    "matplotlib>=3.10.0",
    "opencv-python>=4.10.0.84",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
